plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.jetbrainsKotlinAndroid)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.navigation.safeargs)
    alias(libs.plugins.hilt.dagger)
    alias(libs.plugins.ksp)
}

android {
    namespace 'com.authentication.auth'
    compileSdk 35

    defaultConfig {
        minSdk 25
        testOptions.targetSdk = 34
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
    kotlin{
        jvmToolchain(21)
    }
    buildFeatures {
        compose = true
    }
}

dependencies {
    api(libs.androidx.appcompat)
    api(libs.android.material)
    api(libs.joda.time)
    api(libs.androidx.test.core)
    api(libs.androidx.lifecycle.runtime.ktx)
    api(libs.androidx.ui.compose)
    api(libs.androidx.ui.compose.graphics)
    api(libs.androidx.junit)
    api(libs.androidx.ext)
    api(libs.androidx.test.core)
    api(libs.androidx.espresso.core)
    api(libs.mockito.core)
    api(libs.mockito.android)
    api(libs.coroutine.test)
    api(libs.androidx.core.ktx)

    //Room
    implementation(libs.room)
    implementation(libs.room.ktx)
    ksp(libs.room.compiler.ksp)

    //Dagger hilt
    implementation(libs.dagger.hilt)
    ksp(libs.dagger.hilt.compiler.ksp)

    //Coroutine
    api(libs.coroutine.android)
    api(libs.coroutine.core)

    //Retrofit
    api(libs.retrofit2)
    api(libs.retrofit2.converter.gson)

    //Compose
    api(platform(libs.androidx.compose.bom))
    api(platform(libs.androidx.compose.bom))
    api(libs.androidx.compose.material3)
    api(libs.androidx.compose.constraint.layout)
    api(libs.androidx.compose.activity)
    api(libs.androidx.compose.viewmodel)
    api(libs.androidx.compose.livedata)
    api(libs.androidx.compose.icons.core)
    api(libs.androidx.compose.icons.extended)
    api(libs.androidx.compose.window.size)
    api(libs.androidx.compose.navigation)
    api(libs.androidx.compose.lifecycle.runtime)
    api(libs.androidx.ui.compose.tooling.preview)
    api(libs.androidx.ui.compose.tooling.debug)
    api(libs.androidx.ui.compose.test.junit4)
    api(libs.androidx.ui.compose.test.manifest)
    api(libs.androidx.compose.animation)
    implementation project(':network_state')
}
