[versions]
## Dependencies version
coreKtx = "1.13.0"
appcompat = "1.6.1"
material = "1.11.0"
constraintlayout = "2.1.4"
androidxNavigation = "2.7.7"
preference = "1.2.1"
joda = "2.12.7"
core = "1.5.0"
junitVersion = "1.1.5"
junit = "4.13.2"
archCoreTest = "2.2.0"
espressoCore = "3.5.1"
mockito = "5.4.0"
mockito-androidTestImplementation = "2.24.5"
multiDex = "2.0.1"
dotsIndicator = "5.0"
exoplayer = "1.3.1"
room = "2.6.1"
coroutine = "1.8.0"
viewModelLifeCycle = "2.7.0"
activity = "1.9.0"
fragment = "1.6.2"
glideTransform = "4.3.0"
gpuImage = "2.1.0"
piccasso = "4.16.0"
glide = "4.16.0"
retrofit = "2.11.0"

## Plugins versions
agp = "8.3.2"
kotlin = "1.9.22"
navigation = "2.7.7"
hilt = "2.51.1"
ksp = "1.9.22-1.0.17"
kapt = "1.9.22"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidxNavigation" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidxNavigation" }
preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference" }
joda-time = { group = "net.danlew", name = "android.joda", version.ref = "joda" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "core" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-arch = { group = "androidx.arch.core", name = "core-testing", version.ref = "archCoreTest" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockito-android = { group = "org.mockito", name = "mockito-android", version.ref = "mockito-androidTestImplementation" }
multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multiDex" }
dots-indicator = { group = "com.tbuonomo", name = "dotsindicator", version.ref = "dotsIndicator" }

## Exo player
exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "exoplayer" }
exoplayer-dash = { group = "androidx.media3", name = "media3-exoplayer-dash", version.ref = "exoplayer" }
exoplayer-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "exoplayer" }

## Room
room = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler-ksp = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

## Dagger
dagger-hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
dagger-hilt-compiler-ksp = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

## Coroutine
coroutine-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutine" }
coroutine-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutine" }

## LifeCycle
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "viewModelLifeCycle" }
androidx-lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "viewModelLifeCycle" }

## Access to viewmodel
androidx-activity-ktx  = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
androidx-fragment-ktx  = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }

## Glide Round image
glide-transformations = { group = "jp.wasabeef", name = "glide-transformations", version.ref = "glideTransform" }
gpu-image = { group = "jp.co.cyberagent.android", name = "gpuimage", version.ref = "gpuImage" }
piccasso = { group = "com.squareup.picasso", name = "picasso", version.ref = "piccasso" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }

## Retrofit - RxJava
retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit2-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
navigation-safeargs = { id = "androidx.navigation.safeargs", version.ref = "navigation" }
hilt-dagger = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kapt" }

